FROM nginx:latest

ADD ./docker_config/default.conf /etc/nginx/conf.d/default.conf
#COPY ./docker_config/php.ini /usr/local/etc/php/

ADD ./src /var/www/laravel670
RUN chown www-data:www-data -R /var/www/laravel670

RUN apt-get update
RUN apt-get install net-tools -y
